[target.riscv32imac-unknown-none-elf]
runner = "espflash flash --monitor"
# runner = "probe-rs run --chip esp32c6"

[env]
ESP_LOGLEVEL="INFO"
[build]
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "force-frame-pointers",
  "-C", "link-arg=-Trom_functions.x",
]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["alloc", "core"]
